// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9hWU3IUjJP4BxoTcLen4AHZsIoDYmrZY',
    appId: '1:472139794908:web:48dea35df9dc5b71b36719',
    messagingSenderId: '472139794908',
    projectId: 'musika-ba16a',
    authDomain: 'musika-ba16a.firebaseapp.com',
    storageBucket: 'musika-ba16a.appspot.com',
    measurementId: 'G-37134CZ1EK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2jogDVsMukqcUPPdXBMYwlejJVu7Lhe4',
    appId: '1:472139794908:android:f929435de2e4e975b36719',
    messagingSenderId: '472139794908',
    projectId: 'musika-ba16a',
    storageBucket: 'musika-ba16a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0tpEZ2QyedsmWwCgSMrioLV1s4pV2294',
    appId: '1:472139794908:ios:4cc3b0d628052d55b36719',
    messagingSenderId: '472139794908',
    projectId: 'musika-ba16a',
    storageBucket: 'musika-ba16a.appspot.com',
    iosClientId: '472139794908-5mgbhk6j2o33v8hknl4a6403k5b33v08.apps.googleusercontent.com',
    iosBundleId: 'com.example.aipictWin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0tpEZ2QyedsmWwCgSMrioLV1s4pV2294',
    appId: '1:472139794908:ios:89e554fbf6c91d5bb36719',
    messagingSenderId: '472139794908',
    projectId: 'musika-ba16a',
    storageBucket: 'musika-ba16a.appspot.com',
    iosClientId: '472139794908-3afgcrp18b68somachf5a9152h273dm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.aipictWin.RunnerTests',
  );
}
